# FEEDBACK_VALUES_
FEEDBACK_VALUE_STRIP_BUTTONS = 1
FEEDBACK_VALUE_STRIP_CONTROLS = 2
FEEDBACK_VALUE_MASTER_SECTION = 16
FEEDBACK_VALUE_SELECT_ONLY_FEEDBACK = 8192
FEEDBACK_VALUE_USE_SLASH_REPLY = 16384
FEEDBACK_VALUE_REPORT_TRIGGER_STATUS = 32768
FEEDBACK_VALUE_REPORT_MIXER_SCENE = 65536


EMPTY_STRING = ""

SETTING_SERVER_IP = "serverhost"
SETTING_SERVER_PORT = "serverport"

SETTING_CLIENT_IP = "clienthost"
SETTING_CLIENT_PORT = "clientport"

SETTING_ENABLE_TRIGGERS = "triggerpage"
SETTING_ENABLE_MIXER_SCENES = "mixerscenes"


